services:
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5678:5678"
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_HOST=server
      - SERVER_PORT=5678
      - STORAGE_PATH=/tmp/bets.csv
  client_0:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_0
    depends_on:
      - server
    volumes:
      # "host_path:container_path"
      - ./input:/data/input
      - ./output:/data/output
    environment:
      - AGENCY_ID=0
      - INPUT_FILE=/data/input/input-0.csv
      - OUTPUT_FILE=/data/output/output-0.csv
      - SERVER_HOST=server
      - SERVER_PORT=5678
  client_1:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_1
    depends_on:
      - server
    volumes:
      # "host_path:container_path"
      - ./input:/data/input
      - ./output:/data/output
    environment:
      - AGENCY_ID=1
      - INPUT_FILE=/data/input/input-1.csv
      - OUTPUT_FILE=/data/output/output-1.csv
      - SERVER_HOST=server
      - SERVER_PORT=5678
  client_2:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_2
    depends_on:
      - server
    volumes:
      # "host_path:container_path"
      - ./input:/data/input
      - ./output:/data/output
    environment:
      - AGENCY_ID=2
      - INPUT_FILE=/data/input/input-2.csv
      - OUTPUT_FILE=/data/output/output-2.csv
      - SERVER_HOST=server
      - SERVER_PORT=5678
  client_3:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_3
    depends_on:
      - server
    volumes:
      # "host_path:container_path"
      - ./input:/data/input
      - ./output:/data/output
    environment:
      - AGENCY_ID=3
      - INPUT_FILE=/data/input/input-3.csv
      - OUTPUT_FILE=/data/output/output-3.csv
      - SERVER_HOST=server
      - SERVER_PORT=5678
  client_4:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    container_name: client_4
    depends_on:
      - server
    volumes:
      # "host_path:container_path"
      - ./input:/data/input
      - ./output:/data/output
    environment:
      - AGENCY_ID=4
      - INPUT_FILE=/data/input/input-4.csv
      - OUTPUT_FILE=/data/output/output-4.csv
      - SERVER_HOST=server
      - SERVER_PORT=5678
